### ISSUE TITLE
'vagrant up' fails with Authentication failure

### ISSUE THREAD

**Issue by lsim** [holms/vagrant-centos7-box#6]
Versions of stuff
- osx 10.11.6 
- virtualbox 5.1.2.r108956
- vagrant 1.8.5

Since this image seems to have stayed the same for quite a while, I guess the issue could come from a change to vagrant?

Is this image working for other people? A colleague of mine had problems and I went to work to reproduce the issue. As soon as I made vagrant redownload the image, I had the same problem. It looks as follows:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos7-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'centos7-base' (v0) for provider: virtualbox
    default: Downloading: https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box
==> default: Successfully added box 'centos7-base' (v0) for 'virtualbox'!
==> default: Importing base box 'centos7-base'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: cetreacentos7_default_1470218823538_37534
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2201.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2201 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

Maybe I'm missing something obvious - but this image has worked well for us for a long time. Hope someone can help.

**Comment by lsim** [comment]
I didn't exactly find a fix, but I can at least get running again by adding the following to my Vagrantfile: 

config.ssh.insert_key = false

Found it here: http://superuser.com/questions/872499/can-i-get-vagrant-to-keep-the-insecure-keys

**Comment by holms** [comment]
This only happen due to incorrect Vagrantfile:) which is even not in this repo. Those "insert_key's" always brings trouble to vagrant community. I've basically dropped VM's personally and move to docker.

**Comment by lsim** [comment]
I guess I should have mentioned that the Vagrantfile has also stayed unchanged (and working) for a year or longer. It's pretty basic:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  #config.vm.host_name = "centos7-base"
  config.vm.box = "centos7-base"
  config.vm.box_url = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
  config.vm.network :private_network, ip: "192.168.34.10"

  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

config.vm.provision :shell, :path => "install.sh"
end
```

If anyone can see a problem, please feel free to share :)

**Comment by holms** [comment]
Ok ill include this to readme file :)
